language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
addons:
  packages:
    - cmake
    - libcurl14-openssl-dev
