[package]
name = "git-journal"
version = "1.0.0"
license = "MIT"
readme = "README.md"
keywords = ["parser", "git", "log", "changelog", "journal"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/git-journal"

[dependencies]
clap = { version = "2.11.0", features = ["yaml"] }
git2 = "0.4.4"
chrono = "0.2.25"
nom = "1.2.4"
regex = "0.1.74"
lazy_static = "0.2.1"

[[bin]]
name = "git-journal"
path = "src/main.rs"

