[package]
name = "git-journal"
version = "1.0.0"
license = "MIT"
readme = "README.md"
keywords = ["parser", "git", "log", "changelog", "journal"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/git-journal"

[dependencies]
chrono = "*"
clap = { version = "*", features = ["yaml"] }
git2 = "*"
lazy_static = "*"
nom = { version = "*", features = ["regexp_macros"] }
regex = "*"
rustc-serialize = "*"
term = "*"
toml = "*"

[[bin]]
name = "git-journal"
path = "src/main.rs"
doc = false

