[package]
name = "git-journal"
version = "1.3.0"
license = "MIT"
readme = "README.md"
keywords = ["parser", "git", "log", "changelog", "journal"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/git-journal"
homepage = "https://github.com/saschagrunert/git-journal"
documentation = "https://docs.rs/git-journal"
description = "The Git Commit Message and Changelog Generation Framework"

[lib]
name = "gitjournal"

[dependencies]
chrono = "0"
clap = { version = "2", features = ["yaml"] }
git2 = "0"
lazy_static = "0"
log = "0"
nom = { version = "2", features = ["regexp_macros"] }
regex = "0"
rayon = "0"
rustc-serialize = "0"
term = "0"
toml = "0"

[[bin]]
name = "git-journal"
path = "src/main.rs"
doc = false

