[package]
name = "git-journal"
version = "1.0.0"
license = "MIT"
readme = "README.md"
keywords = ["parser", "git", "log", "changelog", "journal"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/git-journal"

[dependencies]
clap = { version = "*", features = ["yaml"] }
git2 = "*"
chrono = "*"
nom = "*"
regex = "*"
lazy_static = "*"
term = "*"
toml = "*"
rustc-serialize = "*"

[[bin]]
name = "git-journal"
path = "src/main.rs"

