[package]
name = "git-journal"
version = "1.4.1"
license = "MIT"
readme = "README.md"
keywords = ["parser", "git", "log", "changelog", "journal"]
authors = ["Sascha Grunert <mail@saschagruenrt.de>"]
repository = "https://github.com/saschagrunert/git-journal"
homepage = "https://github.com/saschagrunert/git-journal"
documentation = "https://docs.rs/git-journal"
description = "The Git Commit Message and Changelog Generation Framework"
categories = ["command-line-utilities"]

[badges]
travis-ci = { repository = "saschagrunert/git-journal", branch = "master" }
appveyor = { repository = "saschagrunert/git-journal", branch = "master", service = "github" }

[lib]
name = "gitjournal"

[dependencies]
chrono = "0"
clap = { version = "2", features = ["yaml"] }
git2 = "0"
lazy_static = "0"
log = "0"
mowl = "1"
nom = { version = "2", features = ["regexp_macros"] }
regex = "0.1"
rayon = "0"
serde = "0"
serde_derive = "0"
term = "0"
toml = "0"

[[bin]]
name = "git-journal"
path = "src/main.rs"
doc = false
